version: "3.9"
services:
  browseros:
    build: .
    image: my/browseros-webtop:latest
    container_name: browseros
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
      # Optional: enable hardware accel if host has NVIDIA
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - browseros_config:/config
    # noVNC is on 3000 inside; don't publish ports if Traefik is used
    # ports:
    #   - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.browseros.rule=Host(`browseros.yourdomain.com`)"
      - "traefik.http.routers.browseros.entrypoints=websecure"
      - "traefik.http.routers.browseros.tls.certresolver=letsencrypt"
      - "traefik.http.services.browseros.loadbalancer.server.port=3000"
    restart: unless-stopped
    # For NVIDIA GPU passthrough (optional)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
    #           driver: nvidia
volumes:
  browseros_config:
